
social:
  discord: https://kubos-preservation-group.github.io/DiscordRedirect/
  github: https://github.com/KubOS-Preservation-Group/


permalink: /blog/:title

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - 