
social:
  discord: https://kubos-preservation-group.github.io/DiscordRedirect/
  github: https://github.com/KubOS-Preservation-Group/


permalink: /blog/:title

authors:
  adrian:
    name: Adrian Edwards
    url: https://www.adriancedwards.com
    avatar: /images/avatars/user-06.jpg

    
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - 